name: Running Action- div
on:
  workflow_dispatch:
    inputs:
      PAYLOAD:
        description: 'Payload'
        required: false

jobs:
  run_docker_image:
    runs-on: self-hosted
    container: ghcr.io/ashish-ramrakhiani/github-actions-tidyverse-vm:v1.0.vm
    env:
      SECRET_PAYLOAD: ${{ secrets.SECRET_PAYLOAD }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PAYLOAD_REPO: ${{ vars.PAYLOAD_REPO }}
      PAYLOAD: ${{ github.event.inputs.PAYLOAD }}
    steps:
    - name: run Rscript
      run: |
        cd /action
        Rscript faasr_start_invoke_github-actions.R
